import 'package:cloud_firestore/cloud_firestore.dart';

class JobsModel {
  String docId;
  Timestamp dateQ;
  String createdBy;
  String currentEmpId;
  bool forSorting; //JobsOnQueue
  bool riderPickup;
  int customerId;
  String customerName;
  bool perKilo;
  bool perLoad;
  int finalKilo;
  int finalLoad;
  int finalPrice;
  bool regular;
  bool sayosabon;
  bool addOn;
  Timestamp needOn;
  bool fold;
  bool mix;
  int basket;
  int ebag;
  int sako;
  String remarks;
  bool unpaid;
  bool paidcash;
  bool paidgcash;
  bool paidgcashverified;
  String paymentReceivedBy;
  Timestamp paidD;
  Timestamp dateO;
  int itemId1;
  String itemName1;
  int itemPcs1;
  int itemPrice1;
  int itemPriceTotal1;
  int itemId2;
  String itemName2;
  int itemPcs2;
  int itemPrice2;
  int itemPriceTotal2;
  int itemId3;
  String itemName3;
  int itemPcs3;
  int itemPrice3;
  int itemPriceTotal3;
  int itemId4;
  String itemName4;
  int itemPcs4;
  int itemPrice4;
  int itemPriceTotal4;
  int itemId5;
  String itemName5;
  int itemPcs5;
  int itemPrice5;
  int itemPriceTotal5;
  int itemId6;
  String itemName6;
  int itemPcs6;
  int itemPrice6;
  int itemPriceTotal6;
  int itemId7;
  String itemName7;
  int itemPcs7;
  int itemPrice7;
  int itemPriceTotal7;
  int itemId8;
  String itemName8;
  int itemPcs8;
  int itemPrice8;
  int itemPriceTotal8;
  int itemId9;
  String itemName9;
  int itemPcs9;
  int itemPrice9;
  int itemPriceTotal9;
  int itemId10;
  String itemName10;
  int itemPcs10;
  int itemPrice10;
  int itemPriceTotal10;
  int itemId11;
  String itemName11;
  int itemPcs11;
  int itemPrice11;
  int itemPriceTotal11;
  int itemId12;
  String itemName12;
  int itemPcs12;
  int itemPrice12;
  int itemPriceTotal12;
  int itemId13;
  String itemName13;
  int itemPcs13;
  int itemPrice13;
  int itemPriceTotal13;
  int itemId14;
  String itemName14;
  int itemPcs14;
  int itemPrice14;
  int itemPriceTotal14;
  int itemId15;
  String itemName15;
  int itemPcs15;
  int itemPrice15;
  int itemPriceTotal15;
  int itemId16;
  String itemName16;
  int itemPcs16;
  int itemPrice16;
  int itemPriceTotal16;
  int itemId17;
  String itemName17;
  int itemPcs17;
  int itemPrice17;
  int itemPriceTotal17;
  int itemId18;
  String itemName18;
  int itemPcs18;
  int itemPrice18;
  int itemPriceTotal18;
  int itemId19;
  String itemName19;
  int itemPcs19;
  int itemPrice19;
  int itemPriceTotal19;
  int itemId20;
  String itemName20;
  int itemPcs20;
  int itemPrice20;
  int itemPriceTotal20;
  int jobsId; //JobsOnGoing
  bool waiting;
  bool washing;
  bool drying;
  bool folding;
  Timestamp dateD; //JobsDone
  bool waitCustomerPickup;
  bool waitRiderDelivery;
  bool nasaCustomerNa;
  bool waitingOneWeek;
  bool waitingTwoWeeks;
  bool forDisposal;
  bool disposed;

  JobsModel({
    required this.docId,
    required this.dateQ,
    required this.createdBy,
    required this.currentEmpId,
    required this.forSorting, // JobsOnQueue
    required this.riderPickup,
    required this.customerId,
    required this.customerName,
    required this.perKilo,
    required this.perLoad,
    required this.finalKilo,
    required this.finalLoad,
    required this.finalPrice,
    required this.regular,
    required this.sayosabon,
    required this.addOn,
    required this.needOn,
    required this.fold,
    required this.mix,
    required this.basket,
    required this.ebag,
    required this.sako,
    required this.remarks,
    required this.unpaid,
    required this.paidcash,
    required this.paidgcash,
    required this.paidgcashverified,
    required this.paymentReceivedBy,
    required this.paidD,
    required this.dateO,
    required this.itemId1,
    required this.itemName1,
    required this.itemPcs1,
    required this.itemPrice1,
    required this.itemPriceTotal1,
    required this.itemId2,
    required this.itemName2,
    required this.itemPcs2,
    required this.itemPrice2,
    required this.itemPriceTotal2,
    required this.itemId3,
    required this.itemName3,
    required this.itemPcs3,
    required this.itemPrice3,
    required this.itemPriceTotal3,
    required this.itemId4,
    required this.itemName4,
    required this.itemPcs4,
    required this.itemPrice4,
    required this.itemPriceTotal4,
    required this.itemId5,
    required this.itemName5,
    required this.itemPcs5,
    required this.itemPrice5,
    required this.itemPriceTotal5,
    required this.itemId6,
    required this.itemName6,
    required this.itemPcs6,
    required this.itemPrice6,
    required this.itemPriceTotal6,
    required this.itemId7,
    required this.itemName7,
    required this.itemPcs7,
    required this.itemPrice7,
    required this.itemPriceTotal7,
    required this.itemId8,
    required this.itemName8,
    required this.itemPcs8,
    required this.itemPrice8,
    required this.itemPriceTotal8,
    required this.itemId9,
    required this.itemName9,
    required this.itemPcs9,
    required this.itemPrice9,
    required this.itemPriceTotal9,
    required this.itemId10,
    required this.itemName10,
    required this.itemPcs10,
    required this.itemPrice10,
    required this.itemPriceTotal10,
    required this.itemId11,
    required this.itemName11,
    required this.itemPcs11,
    required this.itemPrice11,
    required this.itemPriceTotal11,
    required this.itemId12,
    required this.itemName12,
    required this.itemPcs12,
    required this.itemPrice12,
    required this.itemPriceTotal12,
    required this.itemId13,
    required this.itemName13,
    required this.itemPcs13,
    required this.itemPrice13,
    required this.itemPriceTotal13,
    required this.itemId14,
    required this.itemName14,
    required this.itemPcs14,
    required this.itemPrice14,
    required this.itemPriceTotal14,
    required this.itemId15,
    required this.itemName15,
    required this.itemPcs15,
    required this.itemPrice15,
    required this.itemPriceTotal15,
    required this.itemId16,
    required this.itemName16,
    required this.itemPcs16,
    required this.itemPrice16,
    required this.itemPriceTotal16,
    required this.itemId17,
    required this.itemName17,
    required this.itemPcs17,
    required this.itemPrice17,
    required this.itemPriceTotal17,
    required this.itemId18,
    required this.itemName18,
    required this.itemPcs18,
    required this.itemPrice18,
    required this.itemPriceTotal18,
    required this.itemId19,
    required this.itemName19,
    required this.itemPcs19,
    required this.itemPrice19,
    required this.itemPriceTotal19,
    required this.itemId20,
    required this.itemName20,
    required this.itemPcs20,
    required this.itemPrice20,
    required this.itemPriceTotal20,
    required this.jobsId, // JobsOnGoing
    required this.waiting,
    required this.washing,
    required this.drying,
    required this.folding,
    required this.dateD, // JobsDone
    required this.waitCustomerPickup,
    required this.waitRiderDelivery,
    required this.nasaCustomerNa,
    required this.waitingOneWeek,
    required this.waitingTwoWeeks,
    required this.forDisposal,
    required this.disposed,
  });

  JobsModel coyWith({
    String? docId,
    Timestamp? dateQ,
    String? createdBy,
    String? currentEmpId,
    bool? forSorting, // JobsOnQueue
    bool? riderPickup,
    int? customerId,
    String? customerName,
    bool? perKilo,
    bool? perLoad,
    int? finalKilo,
    int? finalLoad,
    int? finalPrice,
    bool? regular,
    bool? sayosabon,
    bool? addOn,
    Timestamp? needOn,
    bool? fold,
    bool? mix,
    int? basket,
    int? ebag,
    int? sako,
    String? remarks,
    bool? unpaid,
    bool? paidcash,
    bool? paidgcash,
    bool? paidgcashverified,
    String? paymentReceivedBy,
    Timestamp? paidD,
    Timestamp? dateO,
    int? itemId1,
    String? itemName1,
    int? itemPcs1,
    int? itemPrice1,
    int? itemPriceTotal1,
    int? itemId2,
    String? itemName2,
    int? itemPcs2,
    int? itemPrice2,
    int? itemPriceTotal2,
    int? itemId3,
    String? itemName3,
    int? itemPcs3,
    int? itemPrice3,
    int? itemPriceTotal3,
    int? itemId4,
    String? itemName4,
    int? itemPcs4,
    int? itemPrice4,
    int? itemPriceTotal4,
    int? itemId5,
    String? itemName5,
    int? itemPcs5,
    int? itemPrice5,
    int? itemPriceTotal5,
    int? itemId6,
    String? itemName6,
    int? itemPcs6,
    int? itemPrice6,
    int? itemPriceTotal6,
    int? itemId7,
    String? itemName7,
    int? itemPcs7,
    int? itemPrice7,
    int? itemPriceTotal7,
    int? itemId8,
    String? itemName8,
    int? itemPcs8,
    int? itemPrice8,
    int? itemPriceTotal8,
    int? itemId9,
    String? itemName9,
    int? itemPcs9,
    int? itemPrice9,
    int? itemPriceTotal9,
    int? itemId10,
    String? itemName10,
    int? itemPcs10,
    int? itemPrice10,
    int? itemPriceTotal10,
    int? itemId11,
    String? itemName11,
    int? itemPcs11,
    int? itemPrice11,
    int? itemPriceTotal11,
    int? itemId12,
    String? itemName12,
    int? itemPcs12,
    int? itemPrice12,
    int? itemPriceTotal12,
    int? itemId13,
    String? itemName13,
    int? itemPcs13,
    int? itemPrice13,
    int? itemPriceTotal13,
    int? itemId14,
    String? itemName14,
    int? itemPcs14,
    int? itemPrice14,
    int? itemPriceTotal14,
    int? itemId15,
    String? itemName15,
    int? itemPcs15,
    int? itemPrice15,
    int? itemPriceTotal15,
    int? itemId16,
    String? itemName16,
    int? itemPcs16,
    int? itemPrice16,
    int? itemPriceTotal16,
    int? itemId17,
    String? itemName17,
    int? itemPcs17,
    int? itemPrice17,
    int? itemPriceTotal17,
    int? itemId18,
    String? itemName18,
    int? itemPcs18,
    int? itemPrice18,
    int? itemPriceTotal18,
    int? itemId19,
    String? itemName19,
    int? itemPcs19,
    int? itemPrice19,
    int? itemPriceTotal19,
    int? itemId20,
    String? itemName20,
    int? itemPcs20,
    int? itemPrice20,
    int? itemPriceTotal20,
    int? jobsId, // JobsOnGoing
    bool? waiting,
    bool? washing,
    bool? drying,
    bool? folding,
    Timestamp? dateD, // JobsDone
    bool? waitCustomerPickup,
    bool? waitRiderDelivery,
    bool? nasaCustomerNa,
    bool? waitingOneWeek,
    bool? waitingTwoWeeks,
    bool? forDisposal,
    bool? disposed,
  }) {
    return JobsModel(
      docId: docId ?? this.docId,
      dateQ: dateQ ?? this.dateQ,
      createdBy: createdBy ?? this.createdBy,
      currentEmpId: currentEmpId ?? this.currentEmpId,
      forSorting: forSorting ?? this.forSorting,
      riderPickup: riderPickup ?? this.riderPickup,
      customerId: customerId ?? this.customerId,
      customerName: customerName ?? this.customerName,
      perKilo: perKilo ?? this.perKilo,
      perLoad: perLoad ?? this.perLoad,
      finalKilo: finalKilo ?? this.finalKilo,
      finalLoad: finalLoad ?? this.finalLoad,
      finalPrice: finalPrice ?? this.finalPrice,
      regular: regular ?? this.regular,
      sayosabon: sayosabon ?? this.sayosabon,
      addOn: addOn ?? this.addOn,
      needOn: needOn ?? this.needOn,
      fold: fold ?? this.fold,
      mix: mix ?? this.mix,
      basket: basket ?? this.basket,
      ebag: ebag ?? this.ebag,
      sako: sako ?? this.sako,
      remarks: remarks ?? this.remarks,
      unpaid: unpaid ?? this.unpaid,
      paidcash: paidcash ?? this.paidcash,
      paidgcash: paidgcash ?? this.paidgcash,
      paidgcashverified: paidgcashverified ?? this.paidgcashverified,
      paymentReceivedBy: paymentReceivedBy ?? this.paymentReceivedBy,
      paidD: paidD ?? this.paidD,
      dateO: dateO ?? this.dateO,
      itemId1: itemId1 ?? this.itemId1,
      itemName1: itemName1 ?? this.itemName1,
      itemPcs1: itemPcs1 ?? this.itemPcs1,
      itemPrice1: itemPrice1 ?? this.itemPrice1,
      itemPriceTotal1: itemPriceTotal1 ?? this.itemPriceTotal1,
      itemId2: itemId2 ?? this.itemId2,
      itemName2: itemName2 ?? this.itemName2,
      itemPcs2: itemPcs2 ?? this.itemPcs2,
      itemPrice2: itemPrice2 ?? this.itemPrice2,
      itemPriceTotal2: itemPriceTotal2 ?? this.itemPriceTotal2,
      itemId3: itemId3 ?? this.itemId3,
      itemName3: itemName3 ?? this.itemName3,
      itemPcs3: itemPcs3 ?? this.itemPcs3,
      itemPrice3: itemPrice3 ?? this.itemPrice3,
      itemPriceTotal3: itemPriceTotal3 ?? this.itemPriceTotal3,
      itemId4: itemId4 ?? this.itemId4,
      itemName4: itemName4 ?? this.itemName4,
      itemPcs4: itemPcs4 ?? this.itemPcs4,
      itemPrice4: itemPrice4 ?? this.itemPrice4,
      itemPriceTotal4: itemPriceTotal4 ?? this.itemPriceTotal4,
      itemId5: itemId5 ?? this.itemId5,
      itemName5: itemName5 ?? this.itemName5,
      itemPcs5: itemPcs5 ?? this.itemPcs5,
      itemPrice5: itemPrice5 ?? this.itemPrice5,
      itemPriceTotal5: itemPriceTotal5 ?? this.itemPriceTotal5,
      itemId6: itemId6 ?? this.itemId6,
      itemName6: itemName6 ?? this.itemName6,
      itemPcs6: itemPcs6 ?? this.itemPcs6,
      itemPrice6: itemPrice6 ?? this.itemPrice6,
      itemPriceTotal6: itemPriceTotal6 ?? this.itemPriceTotal6,
      itemId7: itemId7 ?? this.itemId7,
      itemName7: itemName7 ?? this.itemName7,
      itemPcs7: itemPcs7 ?? this.itemPcs7,
      itemPrice7: itemPrice7 ?? this.itemPrice7,
      itemPriceTotal7: itemPriceTotal7 ?? this.itemPriceTotal7,
      itemId8: itemId8 ?? this.itemId8,
      itemName8: itemName8 ?? this.itemName8,
      itemPcs8: itemPcs8 ?? this.itemPcs8,
      itemPrice8: itemPrice8 ?? this.itemPrice8,
      itemPriceTotal8: itemPriceTotal8 ?? this.itemPriceTotal8,
      itemId9: itemId9 ?? this.itemId9,
      itemName9: itemName9 ?? this.itemName9,
      itemPcs9: itemPcs9 ?? this.itemPcs9,
      itemPrice9: itemPrice9 ?? this.itemPrice9,
      itemPriceTotal9: itemPriceTotal9 ?? this.itemPriceTotal9,
      itemId10: itemId10 ?? this.itemId10,
      itemName10: itemName10 ?? this.itemName10,
      itemPcs10: itemPcs10 ?? this.itemPcs10,
      itemPrice10: itemPrice10 ?? this.itemPrice10,
      itemPriceTotal10: itemPriceTotal10 ?? this.itemPriceTotal10,
      itemId11: itemId11 ?? this.itemId11,
      itemName11: itemName11 ?? this.itemName11,
      itemPcs11: itemPcs11 ?? this.itemPcs11,
      itemPrice11: itemPrice11 ?? this.itemPrice11,
      itemPriceTotal11: itemPriceTotal11 ?? this.itemPriceTotal11,
      itemId12: itemId12 ?? this.itemId12,
      itemName12: itemName12 ?? this.itemName12,
      itemPcs12: itemPcs12 ?? this.itemPcs12,
      itemPrice12: itemPrice12 ?? this.itemPrice12,
      itemPriceTotal12: itemPriceTotal12 ?? this.itemPriceTotal12,
      itemId13: itemId13 ?? this.itemId13,
      itemName13: itemName13 ?? this.itemName13,
      itemPcs13: itemPcs13 ?? this.itemPcs13,
      itemPrice13: itemPrice13 ?? this.itemPrice13,
      itemPriceTotal13: itemPriceTotal13 ?? this.itemPriceTotal13,
      itemId14: itemId14 ?? this.itemId14,
      itemName14: itemName14 ?? this.itemName14,
      itemPcs14: itemPcs14 ?? this.itemPcs14,
      itemPrice14: itemPrice14 ?? this.itemPrice14,
      itemPriceTotal14: itemPriceTotal14 ?? this.itemPriceTotal14,
      itemId15: itemId15 ?? this.itemId15,
      itemName15: itemName15 ?? this.itemName15,
      itemPcs15: itemPcs15 ?? this.itemPcs15,
      itemPrice15: itemPrice15 ?? this.itemPrice15,
      itemPriceTotal15: itemPriceTotal15 ?? this.itemPriceTotal15,
      itemId16: itemId16 ?? this.itemId16,
      itemName16: itemName16 ?? this.itemName16,
      itemPcs16: itemPcs16 ?? this.itemPcs16,
      itemPrice16: itemPrice16 ?? this.itemPrice16,
      itemPriceTotal16: itemPriceTotal16 ?? this.itemPriceTotal16,
      itemId17: itemId17 ?? this.itemId17,
      itemName17: itemName17 ?? this.itemName17,
      itemPcs17: itemPcs17 ?? this.itemPcs17,
      itemPrice17: itemPrice17 ?? this.itemPrice17,
      itemPriceTotal17: itemPriceTotal17 ?? this.itemPriceTotal17,
      itemId18: itemId18 ?? this.itemId18,
      itemName18: itemName18 ?? this.itemName18,
      itemPcs18: itemPcs18 ?? this.itemPcs18,
      itemPrice18: itemPrice18 ?? this.itemPrice18,
      itemPriceTotal18: itemPriceTotal18 ?? this.itemPriceTotal18,
      itemId19: itemId19 ?? this.itemId19,
      itemName19: itemName19 ?? this.itemName19,
      itemPcs19: itemPcs19 ?? this.itemPcs19,
      itemPrice19: itemPrice19 ?? this.itemPrice19,
      itemPriceTotal19: itemPriceTotal19 ?? this.itemPriceTotal19,
      itemId20: itemId20 ?? this.itemId20,
      itemName20: itemName20 ?? this.itemName20,
      itemPcs20: itemPcs20 ?? this.itemPcs20,
      itemPrice20: itemPrice20 ?? this.itemPrice20,
      itemPriceTotal20: itemPriceTotal20 ?? this.itemPriceTotal20,
      jobsId: jobsId ?? this.jobsId,
      waiting: waiting ?? this.waiting,
      washing: washing ?? this.washing,
      drying: drying ?? this.drying,
      folding: folding ?? this.folding,
      dateD: dateD ?? this.dateD,
      waitCustomerPickup: waitCustomerPickup ?? this.waitCustomerPickup,
      waitRiderDelivery: waitRiderDelivery ?? this.waitRiderDelivery,
      nasaCustomerNa: nasaCustomerNa ?? this.nasaCustomerNa,
      waitingOneWeek: waitingOneWeek ?? this.waitingOneWeek,
      waitingTwoWeeks: waitingTwoWeeks ?? this.waitingTwoWeeks,
      forDisposal: forDisposal ?? this.forDisposal,
      disposed: disposed ?? this.disposed,
    );
  }

  JobsModel.fromJson(Map<String, dynamic> json)
      : this(
          docId: json['A0_DocId']! as String,
          dateQ: json['A1_DateQ']! as Timestamp,
          createdBy: json['A1a_CreatedBy']! as String,
          currentEmpId: json['A1b_CurrentEmpId']! as String,
          forSorting: json['A2_ForSorting']! as bool,
          riderPickup: json['A3_RiderPickup']! as bool,
          customerId: json['A4_CustomerId']! as int,
          customerName: json['A5_CustomerName']! as String,
          perKilo: json['A6_PerKilo']! as bool,
          perLoad: json['A7_PerLoad']! as bool,
          finalKilo: json['A8_FinalKilo']! as int,
          finalLoad: json['A9_FinalLoad']! as int,
          finalPrice: json['A10_FinalPrice']! as int,
          regular: json['A11_Regular']! as bool,
          sayosabon: json['A12_Sayosabon']! as bool,
          addOn: json['A13_AddOn']! as bool,
          needOn: json['A14_NeedOn']! as Timestamp,
          fold: json['A15_Fold']! as bool,
          mix: json['A16_Mix']! as bool,
          basket: json['A17_Basket']! as int,
          ebag: json['A18_Ebag']! as int,
          sako: json['A19_Sako']! as int,
          remarks: json['A20_Remarks']! as String,
          unpaid: json['A21_Unpaid']! as bool,
          paidcash: json['A22_PaidCash']! as bool,
          paidgcash: json['A23_PaidGCash']! as bool,
          paidgcashverified: json['A24_PaidGCashVerified']! as bool,
          paymentReceivedBy: json['A25_PaymentReceivedBy']! as String,
          paidD: json['A26_PaidD']! as Timestamp,
          dateO: json['A27_DateO']! as Timestamp,
          itemId1: json['B1_ItemId1']! as int,
          itemName1: json['B1a_ItemName1']! as String,
          itemPcs1: json['B1b_ItemPcs1']! as int,
          itemPrice1: json['B1c_ItemPrice1']! as int,
          itemPriceTotal1: json['B1d_ItemPriceTotal1']! as int,
          itemId2: json['B2_ItemId2']! as int,
          itemName2: json['B2a_ItemName2']! as String,
          itemPcs2: json['B2b_ItemPcs2']! as int,
          itemPrice2: json['B2c_ItemPrice2']! as int,
          itemPriceTotal2: json['B2d_ItemPriceTotal2']! as int,
          itemId3: json['B3_ItemId3']! as int,
          itemName3: json['B3a_ItemName3']! as String,
          itemPcs3: json['B3b_ItemPcs3']! as int,
          itemPrice3: json['B3c_ItemPrice3']! as int,
          itemPriceTotal3: json['B3d_ItemPriceTotal3']! as int,
          itemId4: json['B4_ItemId4']! as int,
          itemName4: json['B4a_ItemName4']! as String,
          itemPcs4: json['B4b_ItemPcs4']! as int,
          itemPrice4: json['B4c_ItemPrice4']! as int,
          itemPriceTotal4: json['B4d_ItemPriceTotal4']! as int,
          itemId5: json['B5_ItemId5']! as int,
          itemName5: json['B5a_ItemName5']! as String,
          itemPcs5: json['B5b_ItemPcs5']! as int,
          itemPrice5: json['B5c_ItemPrice5']! as int,
          itemPriceTotal5: json['B5d_ItemPriceTotal5']! as int,
          itemId6: json['B6_ItemId6']! as int,
          itemName6: json['B6a_ItemName6']! as String,
          itemPcs6: json['B6b_ItemPcs6']! as int,
          itemPrice6: json['B6c_ItemPrice6']! as int,
          itemPriceTotal6: json['B6d_ItemPriceTotal6']! as int,
          itemId7: json['B7_ItemId7']! as int,
          itemName7: json['B7a_ItemName7']! as String,
          itemPcs7: json['B7b_ItemPcs7']! as int,
          itemPrice7: json['B7c_ItemPrice7']! as int,
          itemPriceTotal7: json['B7d_ItemPriceTotal7']! as int,
          itemId8: json['B8_ItemId8']! as int,
          itemName8: json['B8a_ItemName8']! as String,
          itemPcs8: json['B8b_ItemPcs8']! as int,
          itemPrice8: json['B8c_ItemPrice8']! as int,
          itemPriceTotal8: json['B8d_ItemPriceTotal8']! as int,
          itemId9: json['B9_ItemId9']! as int,
          itemName9: json['B9a_ItemName9']! as String,
          itemPcs9: json['B9b_ItemPcs9']! as int,
          itemPrice9: json['B9c_ItemPrice9']! as int,
          itemPriceTotal9: json['B9d_ItemPriceTotal9']! as int,
          itemId10: json['B10_ItemId10']! as int,
          itemName10: json['B10a_ItemName10']! as String,
          itemPcs10: json['B10b_ItemPcs10']! as int,
          itemPrice10: json['B10c_ItemPrice10']! as int,
          itemPriceTotal10: json['B10d_ItemPriceTotal10']! as int,
          itemId11: json['B11_ItemId11']! as int,
          itemName11: json['B11a_ItemName11']! as String,
          itemPcs11: json['B11b_ItemPcs11']! as int,
          itemPrice11: json['B11c_ItemPrice11']! as int,
          itemPriceTotal11: json['B11d_ItemPriceTotal11']! as int,
          itemId12: json['B12_ItemId12']! as int,
          itemName12: json['B12a_ItemName12']! as String,
          itemPcs12: json['B12b_ItemPcs12']! as int,
          itemPrice12: json['B12c_ItemPrice12']! as int,
          itemPriceTotal12: json['B12d_ItemPriceTotal12']! as int,
          itemId13: json['B13_ItemId13']! as int,
          itemName13: json['B13a_ItemName13']! as String,
          itemPcs13: json['B13b_ItemPcs13']! as int,
          itemPrice13: json['B13c_ItemPrice13']! as int,
          itemPriceTotal13: json['B13d_ItemPriceTotal13']! as int,
          itemId14: json['B14_ItemId14']! as int,
          itemName14: json['B14a_ItemName14']! as String,
          itemPcs14: json['B14b_ItemPcs14']! as int,
          itemPrice14: json['B14c_ItemPrice14']! as int,
          itemPriceTotal14: json['B14d_ItemPriceTotal14']! as int,
          itemId15: json['B15_ItemId15']! as int,
          itemName15: json['B15a_ItemName15']! as String,
          itemPcs15: json['B15b_ItemPcs15']! as int,
          itemPrice15: json['B15c_ItemPrice15']! as int,
          itemPriceTotal15: json['B15d_ItemPriceTotal15']! as int,
          itemId16: json['B16_ItemId16']! as int,
          itemName16: json['B16a_ItemName16']! as String,
          itemPcs16: json['B16b_ItemPcs16']! as int,
          itemPrice16: json['B16c_ItemPrice16']! as int,
          itemPriceTotal16: json['B16d_ItemPriceTotal16']! as int,
          itemId17: json['B17_ItemId17']! as int,
          itemName17: json['B17a_ItemName17']! as String,
          itemPcs17: json['B17b_ItemPcs17']! as int,
          itemPrice17: json['B17c_ItemPrice17']! as int,
          itemPriceTotal17: json['B17d_ItemPriceTotal17']! as int,
          itemId18: json['B18_ItemId18']! as int,
          itemName18: json['B18a_ItemName18']! as String,
          itemPcs18: json['B18b_ItemPcs18']! as int,
          itemPrice18: json['B18c_ItemPrice18']! as int,
          itemPriceTotal18: json['B18d_ItemPriceTotal18']! as int,
          itemId19: json['B19_ItemId19']! as int,
          itemName19: json['B19a_ItemName19']! as String,
          itemPcs19: json['B19b_ItemPcs19']! as int,
          itemPrice19: json['B19c_ItemPrice19']! as int,
          itemPriceTotal19: json['B19d_ItemPriceTotal19']! as int,
          itemId20: json['B20_ItemId20']! as int,
          itemName20: json['B20a_ItemName20']! as String,
          itemPcs20: json['B20b_ItemPcs20']! as int,
          itemPrice20: json['B20c_ItemPrice20']! as int,
          itemPriceTotal20: json['B20d_ItemPriceTotal20']! as int,
          jobsId: json['C0_JobsId']! as int,
          waiting: json['C1_Waiting']! as bool,
          washing: json['C2_Washing']! as bool,
          drying: json['C3_Drying']! as bool,
          folding: json['C4_Folding']! as bool,
          dateD: json['C5_DateD']! as Timestamp,
          waitCustomerPickup: json['C6_WaitCustomerPickup']! as bool,
          waitRiderDelivery: json['C7_WaitRiderDelivery']! as bool,
          nasaCustomerNa: json['C8_NasaCustomerNa']! as bool,
          waitingOneWeek: json['C9_WaitingOneWeek']! as bool,
          waitingTwoWeeks: json['C10_WaitingTwoWeeks']! as bool,
          forDisposal: json['C11_ForDisposal']! as bool,
          disposed: json['C12_Disposed']! as bool,
        );

  Map<String, dynamic> toJson() => {
        'A0_DocId': docId,
        'A1_DateQ': dateQ,
        'A1a_CreatedBy': createdBy,
        'A1b_CurrentEmpId': currentEmpId,
        'A2_ForSorting': forSorting,
        'A3_RiderPickup': riderPickup,
        'A4_CustomerId': customerId,
        'A5_CustomerName': customerName,
        'A6_PerKilo': perKilo,
        'A7_PerLoad': perLoad,
        'A8_FinalKilo': finalKilo,
        'A9_FinalLoad': finalLoad,
        'A10_FinalPrice': finalPrice,
        'A11_Regular': regular,
        'A12_Sayosabon': sayosabon,
        'A13_AddOn': addOn,
        'A14_NeedOn': needOn,
        'A15_Fold': fold,
        'A16_Mix': mix,
        'A17_Basket': basket,
        'A18_Ebag': ebag,
        'A19_Sako': sako,
        'A20_Remarks': remarks,
        'A21_Unpaid': unpaid,
        'A22_PaidCash': paidcash,
        'A23_PaidGCash': paidgcash,
        'A24_PaidGCashVerified': paidgcashverified,
        'A25_PaymentReceivedBy': paymentReceivedBy,
        'A26_PaidD': paidD,
        'A27_DateO': dateO,
        'B1_ItemId1': itemId1,
        'B1a_ItemName1': itemName1,
        'B1b_ItemPcs1': itemPcs1,
        'B1c_ItemPrice1': itemPrice1,
        'B1d_ItemPriceTotal1': itemPriceTotal1,
        'B2_ItemId2': itemId2,
        'B2a_ItemName2': itemName2,
        'B2b_ItemPcs2': itemPcs2,
        'B2c_ItemPrice2': itemPrice2,
        'B2d_ItemPriceTotal2': itemPriceTotal2,
        'B3_ItemId3': itemId3,
        'B3a_ItemName3': itemName3,
        'B3b_ItemPcs3': itemPcs3,
        'B3c_ItemPrice3': itemPrice3,
        'B3d_ItemPriceTotal3': itemPriceTotal3,
        'B4_ItemId4': itemId4,
        'B4a_ItemName4': itemName4,
        'B4b_ItemPcs4': itemPcs4,
        'B4c_ItemPrice4': itemPrice4,
        'B4d_ItemPriceTotal4': itemPriceTotal4,
        'B5_ItemId5': itemId5,
        'B5a_ItemName5': itemName5,
        'B5b_ItemPcs5': itemPcs5,
        'B5c_ItemPrice5': itemPrice5,
        'B5d_ItemPriceTotal5': itemPriceTotal5,
        'B6_ItemId6': itemId6,
        'B6a_ItemName6': itemName6,
        'B6b_ItemPcs6': itemPcs6,
        'B6c_ItemPrice6': itemPrice6,
        'B6d_ItemPriceTotal6': itemPriceTotal6,
        'B7_ItemId7': itemId7,
        'B7a_ItemName7': itemName7,
        'B7b_ItemPcs7': itemPcs7,
        'B7c_ItemPrice7': itemPrice7,
        'B7d_ItemPriceTotal7': itemPriceTotal7,
        'B8_ItemId8': itemId8,
        'B8a_ItemName8': itemName8,
        'B8b_ItemPcs8': itemPcs8,
        'B8c_ItemPrice8': itemPrice8,
        'B8d_ItemPriceTotal8': itemPriceTotal8,
        'B9_ItemId9': itemId9,
        'B9a_ItemName9': itemName9,
        'B9b_ItemPcs9': itemPcs9,
        'B9c_ItemPrice9': itemPrice9,
        'B9d_ItemPriceTotal9': itemPriceTotal9,
        'B10_ItemId10': itemId10,
        'B10a_ItemName10': itemName10,
        'B10b_ItemPcs10': itemPcs10,
        'B10c_ItemPrice10': itemPrice10,
        'B10d_ItemPriceTotal10': itemPriceTotal10,
        'B11_ItemId11': itemId11,
        'B11a_ItemName11': itemName11,
        'B11b_ItemPcs11': itemPcs11,
        'B11c_ItemPrice11': itemPrice11,
        'B11d_ItemPriceTotal11': itemPriceTotal11,
        'B12_ItemId12': itemId12,
        'B12a_ItemName12': itemName12,
        'B12b_ItemPcs12': itemPcs12,
        'B12c_ItemPrice12': itemPrice12,
        'B12d_ItemPriceTotal12': itemPriceTotal12,
        'B13_ItemId13': itemId13,
        'B13a_ItemName13': itemName13,
        'B13b_ItemPcs13': itemPcs13,
        'B13c_ItemPrice13': itemPrice13,
        'B13d_ItemPriceTotal13': itemPriceTotal13,
        'B14_ItemId14': itemId14,
        'B14a_ItemName14': itemName14,
        'B14b_ItemPcs14': itemPcs14,
        'B14c_ItemPrice14': itemPrice14,
        'B14d_ItemPriceTotal14': itemPriceTotal14,
        'B15_ItemId15': itemId15,
        'B15a_ItemName15': itemName15,
        'B15b_ItemPcs15': itemPcs15,
        'B15c_ItemPrice15': itemPrice15,
        'B15d_ItemPriceTotal15': itemPriceTotal15,
        'B16_ItemId16': itemId16,
        'B16a_ItemName16': itemName16,
        'B16b_ItemPcs16': itemPcs16,
        'B16c_ItemPrice16': itemPrice16,
        'B16d_ItemPriceTotal16': itemPriceTotal16,
        'B17_ItemId17': itemId17,
        'B17a_ItemName17': itemName17,
        'B17b_ItemPcs17': itemPcs17,
        'B17c_ItemPrice17': itemPrice17,
        'B17d_ItemPriceTotal17': itemPriceTotal17,
        'B18_ItemId18': itemId18,
        'B18a_ItemName18': itemName18,
        'B18b_ItemPcs18': itemPcs18,
        'B18c_ItemPrice18': itemPrice18,
        'B18d_ItemPriceTotal18': itemPriceTotal18,
        'B19_ItemId19': itemId19,
        'B19a_ItemName19': itemName19,
        'B19b_ItemPcs19': itemPcs19,
        'B19c_ItemPrice19': itemPrice19,
        'B19d_ItemPriceTotal19': itemPriceTotal19,
        'B20_ItemId20': itemId20,
        'B20a_ItemName20': itemName20,
        'B20b_ItemPcs20': itemPcs20,
        'B20c_ItemPrice20': itemPrice20,
        'B20d_ItemPriceTotal20': itemPriceTotal20,
        'C0_JobsId': jobsId,
        'C1_Waiting': waiting,
        'C2_Washing': washing,
        'C3_Drying': drying,
        'C4_Folding': folding,
        'C5_DateD': dateD,
        'C6_WaitCustomerPickup': waitCustomerPickup,
        'C7_WaitRiderDelivery': waitRiderDelivery,
        'C8_NasaCustomerNa': nasaCustomerNa,
        'C9_WaitingOneWeek': waitingOneWeek,
        'C10_WaitingTwoWeeks': waitingTwoWeeks,
        'C11_ForDisposal': forDisposal,
        'C12_Disposed': disposed,
      };
}
