// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyChXE4nw_k-s27PCTIwgM7oIwJtKjJr0ak",
    authDomain: "wash-ko-lang-sit.firebaseapp.com",
    projectId: "wash-ko-lang-sit",
    storageBucket: "wash-ko-lang-sit.firebasestorage.app",
    messagingSenderId: "248306194923",
    appId: "1:248306194923:web:607d219c1d3536cfb7a1ae",
    measurementId: "G-16WPWN06LM",
    // apiKey: 'AIzaSyASvVM-bX6W7-r1-O_u8fbrn5CaFnxVzWQ',
    // appId: '1:248306194923:web:4484ca74bbc01546b7a1ae',
    // messagingSenderId: '248306194923',
    // projectId: 'wash-ko-lang-sit',
    // authDomain: 'wash-ko-lang-sit.firebaseapp.com',
    // storageBucket: 'wash-ko-lang-sit.firebasestorage.app',
    // measurementId: 'G-S5RTGDB4DL',
  );

  //rider db
  static const FirebaseOptions secondaryWeb = FirebaseOptions(
    apiKey: 'AIzaSyAY9RKLaW6ngSCHvQqiujNxpRwJ9kzssgU',
    appId: '1:368198382683:web:1c00691fe118faa041fb7e',
    messagingSenderId: '368198382683',
    projectId: 'zpos-d985c',
    authDomain: 'zpos-d985c.firebaseapp.com',
    storageBucket: 'zpos-d985c.firebasestorage.app',
  );

  //report db
  static const FirebaseOptions thirdWeb = FirebaseOptions(
    apiKey: "AIzaSyDZbBFuPDmvEHEvI94_aCZA5vphxaB39Fc",
    appId: "1:224993515336:web:b76439d1d92884b17b457d",
    messagingSenderId: "224993515336",
    projectId: "splannofb",
    authDomain: "splannofb.firebaseapp.com",
    storageBucket: "splannofb.firebasestorage.app",
  );

  // TODO: Replace with actual forthWeb Firebase project credentials
  //single card db
  static const FirebaseOptions forthWeb = FirebaseOptions(
    apiKey: "AIzaSyCdITzOwEzJ0S3BxeiFWzJyG_QeetguJeU",
    appId: "1:622437507678:web:4a0230dabb6e6161d5cacf",
    messagingSenderId: "622437507678",
    projectId: "signuptest-53277",
    authDomain: "signuptest-53277.firebaseapp.com",
    storageBucket: "signuptest-53277.firebasestorage.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABXoKDWC1JUR1FwE4es4O-glGHGpDFbI8',
    appId: '1:248306194923:android:246830746ad13f22b7a1ae',
    messagingSenderId: '248306194923',
    projectId: 'wash-ko-lang-sit',
    storageBucket: 'wash-ko-lang-sit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ytAz7UQddz6deYxlq4plET7rLQ1Rclg',
    appId: '1:248306194923:ios:7bfae8b2120eabebb7a1ae',
    messagingSenderId: '248306194923',
    projectId: 'wash-ko-lang-sit',
    storageBucket: 'wash-ko-lang-sit.firebasestorage.app',
    iosBundleId: 'com.example.laundryFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ytAz7UQddz6deYxlq4plET7rLQ1Rclg',
    appId: '1:248306194923:ios:7bfae8b2120eabebb7a1ae',
    messagingSenderId: '248306194923',
    projectId: 'wash-ko-lang-sit',
    storageBucket: 'wash-ko-lang-sit.firebasestorage.app',
    iosBundleId: 'com.example.laundryFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChXE4nw_k-s27PCTIwgM7oIwJtKjJr0ak',
    appId: '1:248306194923:web:fae09490ecba4a31b7a1ae',
    messagingSenderId: '248306194923',
    projectId: 'wash-ko-lang-sit',
    authDomain: 'wash-ko-lang-sit.firebaseapp.com',
    storageBucket: 'wash-ko-lang-sit.firebasestorage.app',
    measurementId: 'G-SN8TY0Q9XQ',
  );
}
